---
title: "Homework 4"
author: "Your Name Here"
subtitle: "Spring 2024"
header-includes:
    - \usepackage{amsmath}
    - \usepackage{amsthm}
    - \usepackage{setspace} 
output: pdf_document
---

\onehalfspacing

```{r setup, include=FALSE}
#Use this code chunk to include libraries, and set global options.

knitr::opts_chunk$set(echo = TRUE, 
                      message= FALSE, 
                      warning = FALSE)

library(tidyverse)

```

### Instructions

- This homework is due in Gradescope on Wednesday May 1 by midnight PST. There is a 15 minute grace period and submissions made during this time will not be marked as late. Any work submitted past this period is considered late.  

- Please answer the following questions in the order in which they are posed. 

- Don't forget to (i) make a local copy this document for your work and to (ii) knit the document frequently to make sure there are no compilation errors. 

- When you are done, download the PDF file as instructed in section and submit it in Gradescope.  

* * *

### Exercises

1. (Racial discrimination in the Labor Market) Does racial discrimination exist in the labor market? Or, should racial disparities in the
unemployment rate be attributed to other factors such as racial gaps in educational attainment?
To answer this question, two social scientists conducted the following experiment. In response to newspaper ads, the researchers sent out resumes of fictitious job candidates
to potential employers. They varied only the names of the job applicants while leaving
the other information in the resumes unchanged. For some resumes, stereotypically blacksounding
names such as Lakisha Washington or Jamal Jones were used, whereas other
resumes contained typically white-sounding names such as Emily Walsh or Greg Baker.
The researchers then compared the callback rates between these two groups of resumes and
examined whether the resumes with typical black names received fewer callbacks than those
with stereotypically white names. The positions to which the applications were sent were
either in sales, administrative support, clerical, or customer services.

    The data are in the file `resume.csv`. Each row represents a fictitious job applicant. For example, the second observation contains a resume of Kristin who is a white female who did not receive a callback.

a. Create a table (`tabyl`) summarizing the race of the applicant and whether or not they received a callback. Your table 
   
   - should have the information for each race on different rows
   
   - should append  the row totals for the callback  
   
   - should show the row-wise percentages for each of the cells using (that is, what fraction of the row is in the cell)
   
   - should have the percentages formatted to 2 digits 
   
   - should also have the frequencies in each cell reported 
   
     Show the code, output and also write a couple of sentences summarizing what you learn from the data. (See slide 17 in slidedeck 23)
   
b. Is there evidence of discrimination? Calculate a 95\% confidence interval for the difference in callback rates for black and white applicants. Please state your interval clearly and then write your conclusion in context. (Please use R only as a calculator. Show your calculations and then interpret the confidence interval)
  
  
  
2. (Pooled variance) Suppose $$X_1,X_2,\dots,X_n \overset{i.i.d.}{\sim} Norm(\mu_1, \sigma_0)$$ independently of $$Y_1,Y_2,\dots,Y_m \overset {i.i.d.}{\sim} Norm(\mu_2, \sigma_0).$$

    Consider the pooled estimator of $\sigma^2_0$:
    $$S^2_p = \frac{(n-1)}{n+m-2} S^2_1 + \frac{m-1}{n+m-2} S^2_2$$
    
    where $S^2_1$ and $S^2_2$ are the usual sample variance based on the $X$'s and $Y$'s respectively.
    
    
a. Argue that $\frac{(n-m+2)\:S^2_p}{\sigma_0^2} \sim \chi^2_{n+m-2}$.  

    
b. Argue that 
   $$T = \frac{\bar{X} - \bar{Y} - (\mu_1 - \mu_2)}{S_p \sqrt{\frac{1}{n} + \frac{1}{m}}} \sim t_{n+m-2}$$ 

  
  
3. The STAR (Student-Teacher Achievement Ratio) Project is a four year longitudinal study examining the effect of class size in early grade levels on educational performance and
personal development. This particular study lasted from 1985 to 1989 and involved 11,601 students. During the four years of the study, students were randomly assigned to small classes, regular-sized
classes, or regular-sized classes with an aid.

    We will analyze just a portion of this data to investigate whether test scores are associated with race or not. The data file name is `star.csv`. The names and descriptions of variables in this data set are displayed in the codebook shown below. 

\begin{table}[phtb]

\centering
\begin{tabular}{|p{1in}|p{4.5in}|}   \hline
\texttt{race}    & student’s race  \\
\texttt{classtype} & type of kindergarten class (small = 1, regular = 2, regular with aid = 3) \\
\texttt{g4math}   & total scaled score for math portion of fourth grade standardized test \\
\texttt{g4reading} & total scaled score for reading portion of fourth grade standardized test \\
\texttt{yearssmall} & number of years in small classes \\
\texttt{hsgrad} & high school graduation (did graduate = 1, did not graduate= 0) \\ \hline
    \end{tabular}
\end{table}



a. Write code to calculate the summary statistics indicated in the table below. Then fill in the numbers in table. Be sure to echo your code. 

    \begin{table}[h]
    \caption{Achievement gap between White and Black kids on 4th grade reading and math}
    \begin{tabular}{ccc|cc|cc}
    classtype & race & $n$ & mean\_read & sd\_read & mean\_math & sd\_math  \\ \hline
    Regular & White & & & & &     \\
    Regular & Black & & & & &      \\
    Small & White & & &  &  &    \\ 
    Small & Black & & &  &  &    \\ 
    \end{tabular}
    \end{table}

b. Calculate and report a 95\% t confidence interval for the difference in mean \textbf{reading} scores between black and white students in a regular classroom. You may assume the scores are normally distributed with the same standard deviation. 

    You may only use R as a calculator. Show your code and output.

c. Repeat part b. for the difference in mean \text{math} scores for black and white students in a regular classroom. 


d. Repeat parts b and c for the small classroom.

e.  Fill in the table with your answers from parts b, c and d describing what you have learned from this analysis.

    \begin{table}[h]
    \caption{Achievement gap between White and Black kids on 4th grade reading and math}
    \begin{tabular}{c|p{2in}|p{2in}}
    Classroom & 95\% CI for difference in mean reading scores (black - white) & 95\% CI for difference in mean math scores (black - white)     \\\hline
    Regular & (b) & (c) \\
    Small & (d) &  (d)  \\ 
    \end{tabular}
    \end{table}

