---
title: "Problem Section 1"
subtitle:  "The z test"
graphics: yes
output: pdf_document
header-includes:
    - \usepackage{amsmath, amssymb}
    - \usepackage{framed}\definecolor{shadecolor}{rgb}{0.949,0.949,0.949}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\begin{shaded}

\textbf{Learning Outcomes}

The problems are designed to build conceptual understanding and problem-solving skills. The emphasis is on learning to find, evaluate and build confidence. The specific tasks include: 

   - Perform a large sample z-test for the mean 
   
   - Perform a large sample z-test for a binomial proportion
   
   - Back up and support work with relevant explanations


\end{shaded}

* * *

### Exercises 

1. Suppose $n = 36$ observations are taken from a distribution with (unknown) mean $\mu_0$ and (known) standard deviation $\sigma_0 = 8.0$ for the purpose of testing
$H_0: \mu_0 = 60$ versus $H_1: \mu_0 \neq  60$ at the $\alpha = 0.07$ level of significance. (You may assume the CLT holds)

a. Find the rejection region of the test. That is, what $\bar{x}$ values will you reject the null hypothesis for?

b. Find the Type II error probability of the test when $\mu_0 = 62$. 

c. Find the confidence interval which is the dual of this significance test. Verify that they will lead to consistent conclusions.



2. A manufacturer of rat poison claims that 82.87% of rats will be killed by their formulation. In order to verify the manufacturer's claim, an experiment is conducted where 150 rats are given
the poison, and 115 (76.67%) of them die. 
Does this indicate that the manufacturer has
overestimated the effect of the poison? 

    Answer this question using the exact binomial distribution and also the large sample z test. What conclusion do you draw at a 1% level of significance?

  
3. Suppose we want to test a prediction method on a set of $n$ new test cases. Let $X_i=1$ if the predictor is wrong and 0 otherwise. Each $X_i$ may be regarded as an independent Bernoulli with probability $\pi_0$. Then $$\hat{\pi}_0 = \bar{x} = \frac{1}{n} \sum\limits_{i=1}^{n}x_i$$ is the observed error rate and is the method of moments estimate of the true error rate $\pi_0$.  How large should $n$ be so that we can be 98\% confident that  the observed error rate is within 2% of the true error rate $\pi_0$.  (You may assume the $n$ will be large enough for the CLT to hold)
